/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated.games'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated.leaderboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated.learn.index'
import { Route as AuthenticatedLearnDailyPuzzleRouteImport } from './routes/_authenticated.learn.daily-puzzle'
import { Route as AuthenticatedLearnInteractiveSampleRouteImport } from './routes/_authenticated.learn.interactive-sample'
import { Route as AuthenticatedLearnPracticeGameRouteImport } from './routes/_authenticated.learn.practice-game'
import { Route as AuthenticatedLearnProgressRouteImport } from './routes/_authenticated.learn.progress'
import { Route as AuthenticatedLearnQuizRouteImport } from './routes/_authenticated.learn.quiz'
import { Route as AuthenticatedPlayIndexRouteImport } from './routes/_authenticated.play.index'
import { Route as AuthenticatedPlayComputerRouteImport } from './routes/_authenticated.play.computer'
import { Route as AuthenticatedPlayFriendsRouteImport } from './routes/_authenticated.play.friends'
import { Route as AuthenticatedGameGameIdIndexRouteImport } from './routes/_authenticated.game.$gameId.index'
import { Route as AuthenticatedGameGameIdReplayRouteImport } from './routes/_authenticated.game.$gameId.replay'
import { Route as AuthenticatedLearnCategoryCategoryIdRouteImport } from './routes/_authenticated.learn.category.$categoryId'
import { Route as AuthenticatedLearnLessonLessonIdRouteImport } from './routes/_authenticated.learn.lesson.$lessonId'
import { Route as AuthenticatedLearnLevel1SkillIdRouteImport } from './routes/_authenticated.learn.level1.$skillId'
import { Route as AuthenticatedLearnLevel10SkillIdRouteImport } from './routes/_authenticated.learn.level10.$skillId'
import { Route as AuthenticatedLearnLevel2SkillIdRouteImport } from './routes/_authenticated.learn.level2.$skillId'
import { Route as AuthenticatedLearnLevel3SkillIdRouteImport } from './routes/_authenticated.learn.level3.$skillId'
import { Route as AuthenticatedLearnLevel4SkillIdRouteImport } from './routes/_authenticated.learn.level4.$skillId'
import { Route as AuthenticatedLearnLevel5SkillIdRouteImport } from './routes/_authenticated.learn.level5.$skillId'
import { Route as AuthenticatedLearnLevel6SkillIdRouteImport } from './routes/_authenticated.learn.level6.$skillId'
import { Route as AuthenticatedLearnLevel7SkillIdRouteImport } from './routes/_authenticated.learn.level7.$skillId'
import { Route as AuthenticatedLearnLevel8SkillIdRouteImport } from './routes/_authenticated.learn.level8.$skillId'
import { Route as AuthenticatedLearnLevel9SkillIdRouteImport } from './routes/_authenticated.learn.level9.$skillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnDailyPuzzleRoute =
  AuthenticatedLearnDailyPuzzleRouteImport.update({
    id: '/learn/daily-puzzle',
    path: '/learn/daily-puzzle',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnInteractiveSampleRoute =
  AuthenticatedLearnInteractiveSampleRouteImport.update({
    id: '/learn/interactive-sample',
    path: '/learn/interactive-sample',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnPracticeGameRoute =
  AuthenticatedLearnPracticeGameRouteImport.update({
    id: '/learn/practice-game',
    path: '/learn/practice-game',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnProgressRoute =
  AuthenticatedLearnProgressRouteImport.update({
    id: '/learn/progress',
    path: '/learn/progress',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnQuizRoute = AuthenticatedLearnQuizRouteImport.update({
  id: '/learn/quiz',
  path: '/learn/quiz',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayIndexRoute = AuthenticatedPlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayComputerRoute =
  AuthenticatedPlayComputerRouteImport.update({
    id: '/play/computer',
    path: '/play/computer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayFriendsRoute =
  AuthenticatedPlayFriendsRouteImport.update({
    id: '/play/friends',
    path: '/play/friends',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGameGameIdIndexRoute =
  AuthenticatedGameGameIdIndexRouteImport.update({
    id: '/game/$gameId/',
    path: '/game/$gameId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGameGameIdReplayRoute =
  AuthenticatedGameGameIdReplayRouteImport.update({
    id: '/game/$gameId/replay',
    path: '/game/$gameId/replay',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnCategoryCategoryIdRoute =
  AuthenticatedLearnCategoryCategoryIdRouteImport.update({
    id: '/learn/category/$categoryId',
    path: '/learn/category/$categoryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnLessonLessonIdRoute =
  AuthenticatedLearnLessonLessonIdRouteImport.update({
    id: '/learn/lesson/$lessonId',
    path: '/learn/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnLevel1SkillIdRoute =
  AuthenticatedLearnLevel1SkillIdRouteImport.update({
    id: '/learn/level1/$skillId',
    path: '/learn/level1/$skillId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnLevel10SkillIdRoute =
  AuthenticatedLearnLevel10SkillIdRouteImport.update({
    id: '/learn/level10/$skillId',
    path: '/learn/level10/$skillId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnLevel2SkillIdRoute =
  AuthenticatedLearnLevel2SkillIdRouteImport.update({
    id: '/learn/level2/$skillId',
    path: '/learn/level2/$skillId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnLevel3SkillIdRoute =
  AuthenticatedLearnLevel3SkillIdRouteImport.update({
    id: '/learn/level3/$skillId',
    path: '/learn/level3/$skillId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnLevel4SkillIdRoute =
  AuthenticatedLearnLevel4SkillIdRouteImport.update({
    id: '/learn/level4/$skillId',
    path: '/learn/level4/$skillId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnLevel5SkillIdRoute =
  AuthenticatedLearnLevel5SkillIdRouteImport.update({
    id: '/learn/level5/$skillId',
    path: '/learn/level5/$skillId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnLevel6SkillIdRoute =
  AuthenticatedLearnLevel6SkillIdRouteImport.update({
    id: '/learn/level6/$skillId',
    path: '/learn/level6/$skillId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnLevel7SkillIdRoute =
  AuthenticatedLearnLevel7SkillIdRouteImport.update({
    id: '/learn/level7/$skillId',
    path: '/learn/level7/$skillId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnLevel8SkillIdRoute =
  AuthenticatedLearnLevel8SkillIdRouteImport.update({
    id: '/learn/level8/$skillId',
    path: '/learn/level8/$skillId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnLevel9SkillIdRoute =
  AuthenticatedLearnLevel9SkillIdRouteImport.update({
    id: '/learn/level9/$skillId',
    path: '/learn/level9/$skillId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/games': typeof AuthenticatedGamesRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/learn/daily-puzzle': typeof AuthenticatedLearnDailyPuzzleRoute
  '/learn/interactive-sample': typeof AuthenticatedLearnInteractiveSampleRoute
  '/learn/practice-game': typeof AuthenticatedLearnPracticeGameRoute
  '/learn/progress': typeof AuthenticatedLearnProgressRoute
  '/learn/quiz': typeof AuthenticatedLearnQuizRoute
  '/play/computer': typeof AuthenticatedPlayComputerRoute
  '/play/friends': typeof AuthenticatedPlayFriendsRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/play/': typeof AuthenticatedPlayIndexRoute
  '/game/$gameId/replay': typeof AuthenticatedGameGameIdReplayRoute
  '/learn/category/$categoryId': typeof AuthenticatedLearnCategoryCategoryIdRoute
  '/learn/lesson/$lessonId': typeof AuthenticatedLearnLessonLessonIdRoute
  '/learn/level1/$skillId': typeof AuthenticatedLearnLevel1SkillIdRoute
  '/learn/level10/$skillId': typeof AuthenticatedLearnLevel10SkillIdRoute
  '/learn/level2/$skillId': typeof AuthenticatedLearnLevel2SkillIdRoute
  '/learn/level3/$skillId': typeof AuthenticatedLearnLevel3SkillIdRoute
  '/learn/level4/$skillId': typeof AuthenticatedLearnLevel4SkillIdRoute
  '/learn/level5/$skillId': typeof AuthenticatedLearnLevel5SkillIdRoute
  '/learn/level6/$skillId': typeof AuthenticatedLearnLevel6SkillIdRoute
  '/learn/level7/$skillId': typeof AuthenticatedLearnLevel7SkillIdRoute
  '/learn/level8/$skillId': typeof AuthenticatedLearnLevel8SkillIdRoute
  '/learn/level9/$skillId': typeof AuthenticatedLearnLevel9SkillIdRoute
  '/game/$gameId/': typeof AuthenticatedGameGameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/games': typeof AuthenticatedGamesRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/learn/daily-puzzle': typeof AuthenticatedLearnDailyPuzzleRoute
  '/learn/interactive-sample': typeof AuthenticatedLearnInteractiveSampleRoute
  '/learn/practice-game': typeof AuthenticatedLearnPracticeGameRoute
  '/learn/progress': typeof AuthenticatedLearnProgressRoute
  '/learn/quiz': typeof AuthenticatedLearnQuizRoute
  '/play/computer': typeof AuthenticatedPlayComputerRoute
  '/play/friends': typeof AuthenticatedPlayFriendsRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/play': typeof AuthenticatedPlayIndexRoute
  '/game/$gameId/replay': typeof AuthenticatedGameGameIdReplayRoute
  '/learn/category/$categoryId': typeof AuthenticatedLearnCategoryCategoryIdRoute
  '/learn/lesson/$lessonId': typeof AuthenticatedLearnLessonLessonIdRoute
  '/learn/level1/$skillId': typeof AuthenticatedLearnLevel1SkillIdRoute
  '/learn/level10/$skillId': typeof AuthenticatedLearnLevel10SkillIdRoute
  '/learn/level2/$skillId': typeof AuthenticatedLearnLevel2SkillIdRoute
  '/learn/level3/$skillId': typeof AuthenticatedLearnLevel3SkillIdRoute
  '/learn/level4/$skillId': typeof AuthenticatedLearnLevel4SkillIdRoute
  '/learn/level5/$skillId': typeof AuthenticatedLearnLevel5SkillIdRoute
  '/learn/level6/$skillId': typeof AuthenticatedLearnLevel6SkillIdRoute
  '/learn/level7/$skillId': typeof AuthenticatedLearnLevel7SkillIdRoute
  '/learn/level8/$skillId': typeof AuthenticatedLearnLevel8SkillIdRoute
  '/learn/level9/$skillId': typeof AuthenticatedLearnLevel9SkillIdRoute
  '/game/$gameId': typeof AuthenticatedGameGameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/learn/daily-puzzle': typeof AuthenticatedLearnDailyPuzzleRoute
  '/_authenticated/learn/interactive-sample': typeof AuthenticatedLearnInteractiveSampleRoute
  '/_authenticated/learn/practice-game': typeof AuthenticatedLearnPracticeGameRoute
  '/_authenticated/learn/progress': typeof AuthenticatedLearnProgressRoute
  '/_authenticated/learn/quiz': typeof AuthenticatedLearnQuizRoute
  '/_authenticated/play/computer': typeof AuthenticatedPlayComputerRoute
  '/_authenticated/play/friends': typeof AuthenticatedPlayFriendsRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/_authenticated/play/': typeof AuthenticatedPlayIndexRoute
  '/_authenticated/game/$gameId/replay': typeof AuthenticatedGameGameIdReplayRoute
  '/_authenticated/learn/category/$categoryId': typeof AuthenticatedLearnCategoryCategoryIdRoute
  '/_authenticated/learn/lesson/$lessonId': typeof AuthenticatedLearnLessonLessonIdRoute
  '/_authenticated/learn/level1/$skillId': typeof AuthenticatedLearnLevel1SkillIdRoute
  '/_authenticated/learn/level10/$skillId': typeof AuthenticatedLearnLevel10SkillIdRoute
  '/_authenticated/learn/level2/$skillId': typeof AuthenticatedLearnLevel2SkillIdRoute
  '/_authenticated/learn/level3/$skillId': typeof AuthenticatedLearnLevel3SkillIdRoute
  '/_authenticated/learn/level4/$skillId': typeof AuthenticatedLearnLevel4SkillIdRoute
  '/_authenticated/learn/level5/$skillId': typeof AuthenticatedLearnLevel5SkillIdRoute
  '/_authenticated/learn/level6/$skillId': typeof AuthenticatedLearnLevel6SkillIdRoute
  '/_authenticated/learn/level7/$skillId': typeof AuthenticatedLearnLevel7SkillIdRoute
  '/_authenticated/learn/level8/$skillId': typeof AuthenticatedLearnLevel8SkillIdRoute
  '/_authenticated/learn/level9/$skillId': typeof AuthenticatedLearnLevel9SkillIdRoute
  '/_authenticated/game/$gameId/': typeof AuthenticatedGameGameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/games'
    | '/leaderboard'
    | '/profile'
    | '/settings'
    | '/learn/daily-puzzle'
    | '/learn/interactive-sample'
    | '/learn/practice-game'
    | '/learn/progress'
    | '/learn/quiz'
    | '/play/computer'
    | '/play/friends'
    | '/learn/'
    | '/play/'
    | '/game/$gameId/replay'
    | '/learn/category/$categoryId'
    | '/learn/lesson/$lessonId'
    | '/learn/level1/$skillId'
    | '/learn/level10/$skillId'
    | '/learn/level2/$skillId'
    | '/learn/level3/$skillId'
    | '/learn/level4/$skillId'
    | '/learn/level5/$skillId'
    | '/learn/level6/$skillId'
    | '/learn/level7/$skillId'
    | '/learn/level8/$skillId'
    | '/learn/level9/$skillId'
    | '/game/$gameId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/games'
    | '/leaderboard'
    | '/profile'
    | '/settings'
    | '/learn/daily-puzzle'
    | '/learn/interactive-sample'
    | '/learn/practice-game'
    | '/learn/progress'
    | '/learn/quiz'
    | '/play/computer'
    | '/play/friends'
    | '/learn'
    | '/play'
    | '/game/$gameId/replay'
    | '/learn/category/$categoryId'
    | '/learn/lesson/$lessonId'
    | '/learn/level1/$skillId'
    | '/learn/level10/$skillId'
    | '/learn/level2/$skillId'
    | '/learn/level3/$skillId'
    | '/learn/level4/$skillId'
    | '/learn/level5/$skillId'
    | '/learn/level6/$skillId'
    | '/learn/level7/$skillId'
    | '/learn/level8/$skillId'
    | '/learn/level9/$skillId'
    | '/game/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/games'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/learn/daily-puzzle'
    | '/_authenticated/learn/interactive-sample'
    | '/_authenticated/learn/practice-game'
    | '/_authenticated/learn/progress'
    | '/_authenticated/learn/quiz'
    | '/_authenticated/play/computer'
    | '/_authenticated/play/friends'
    | '/_authenticated/learn/'
    | '/_authenticated/play/'
    | '/_authenticated/game/$gameId/replay'
    | '/_authenticated/learn/category/$categoryId'
    | '/_authenticated/learn/lesson/$lessonId'
    | '/_authenticated/learn/level1/$skillId'
    | '/_authenticated/learn/level10/$skillId'
    | '/_authenticated/learn/level2/$skillId'
    | '/_authenticated/learn/level3/$skillId'
    | '/_authenticated/learn/level4/$skillId'
    | '/_authenticated/learn/level5/$skillId'
    | '/_authenticated/learn/level6/$skillId'
    | '/_authenticated/learn/level7/$skillId'
    | '/_authenticated/learn/level8/$skillId'
    | '/_authenticated/learn/level9/$skillId'
    | '/_authenticated/game/$gameId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/daily-puzzle': {
      id: '/_authenticated/learn/daily-puzzle'
      path: '/learn/daily-puzzle'
      fullPath: '/learn/daily-puzzle'
      preLoaderRoute: typeof AuthenticatedLearnDailyPuzzleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/interactive-sample': {
      id: '/_authenticated/learn/interactive-sample'
      path: '/learn/interactive-sample'
      fullPath: '/learn/interactive-sample'
      preLoaderRoute: typeof AuthenticatedLearnInteractiveSampleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/practice-game': {
      id: '/_authenticated/learn/practice-game'
      path: '/learn/practice-game'
      fullPath: '/learn/practice-game'
      preLoaderRoute: typeof AuthenticatedLearnPracticeGameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/progress': {
      id: '/_authenticated/learn/progress'
      path: '/learn/progress'
      fullPath: '/learn/progress'
      preLoaderRoute: typeof AuthenticatedLearnProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/quiz': {
      id: '/_authenticated/learn/quiz'
      path: '/learn/quiz'
      fullPath: '/learn/quiz'
      preLoaderRoute: typeof AuthenticatedLearnQuizRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play/': {
      id: '/_authenticated/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof AuthenticatedPlayIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play/computer': {
      id: '/_authenticated/play/computer'
      path: '/play/computer'
      fullPath: '/play/computer'
      preLoaderRoute: typeof AuthenticatedPlayComputerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play/friends': {
      id: '/_authenticated/play/friends'
      path: '/play/friends'
      fullPath: '/play/friends'
      preLoaderRoute: typeof AuthenticatedPlayFriendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/game/$gameId/': {
      id: '/_authenticated/game/$gameId/'
      path: '/game/$gameId'
      fullPath: '/game/$gameId/'
      preLoaderRoute: typeof AuthenticatedGameGameIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/game/$gameId/replay': {
      id: '/_authenticated/game/$gameId/replay'
      path: '/game/$gameId/replay'
      fullPath: '/game/$gameId/replay'
      preLoaderRoute: typeof AuthenticatedGameGameIdReplayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/category/$categoryId': {
      id: '/_authenticated/learn/category/$categoryId'
      path: '/learn/category/$categoryId'
      fullPath: '/learn/category/$categoryId'
      preLoaderRoute: typeof AuthenticatedLearnCategoryCategoryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/lesson/$lessonId': {
      id: '/_authenticated/learn/lesson/$lessonId'
      path: '/learn/lesson/$lessonId'
      fullPath: '/learn/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedLearnLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/level1/$skillId': {
      id: '/_authenticated/learn/level1/$skillId'
      path: '/learn/level1/$skillId'
      fullPath: '/learn/level1/$skillId'
      preLoaderRoute: typeof AuthenticatedLearnLevel1SkillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/level10/$skillId': {
      id: '/_authenticated/learn/level10/$skillId'
      path: '/learn/level10/$skillId'
      fullPath: '/learn/level10/$skillId'
      preLoaderRoute: typeof AuthenticatedLearnLevel10SkillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/level2/$skillId': {
      id: '/_authenticated/learn/level2/$skillId'
      path: '/learn/level2/$skillId'
      fullPath: '/learn/level2/$skillId'
      preLoaderRoute: typeof AuthenticatedLearnLevel2SkillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/level3/$skillId': {
      id: '/_authenticated/learn/level3/$skillId'
      path: '/learn/level3/$skillId'
      fullPath: '/learn/level3/$skillId'
      preLoaderRoute: typeof AuthenticatedLearnLevel3SkillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/level4/$skillId': {
      id: '/_authenticated/learn/level4/$skillId'
      path: '/learn/level4/$skillId'
      fullPath: '/learn/level4/$skillId'
      preLoaderRoute: typeof AuthenticatedLearnLevel4SkillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/level5/$skillId': {
      id: '/_authenticated/learn/level5/$skillId'
      path: '/learn/level5/$skillId'
      fullPath: '/learn/level5/$skillId'
      preLoaderRoute: typeof AuthenticatedLearnLevel5SkillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/level6/$skillId': {
      id: '/_authenticated/learn/level6/$skillId'
      path: '/learn/level6/$skillId'
      fullPath: '/learn/level6/$skillId'
      preLoaderRoute: typeof AuthenticatedLearnLevel6SkillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/level7/$skillId': {
      id: '/_authenticated/learn/level7/$skillId'
      path: '/learn/level7/$skillId'
      fullPath: '/learn/level7/$skillId'
      preLoaderRoute: typeof AuthenticatedLearnLevel7SkillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/level8/$skillId': {
      id: '/_authenticated/learn/level8/$skillId'
      path: '/learn/level8/$skillId'
      fullPath: '/learn/level8/$skillId'
      preLoaderRoute: typeof AuthenticatedLearnLevel8SkillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/level9/$skillId': {
      id: '/_authenticated/learn/level9/$skillId'
      path: '/learn/level9/$skillId'
      fullPath: '/learn/level9/$skillId'
      preLoaderRoute: typeof AuthenticatedLearnLevel9SkillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedLearnDailyPuzzleRoute: typeof AuthenticatedLearnDailyPuzzleRoute
  AuthenticatedLearnInteractiveSampleRoute: typeof AuthenticatedLearnInteractiveSampleRoute
  AuthenticatedLearnPracticeGameRoute: typeof AuthenticatedLearnPracticeGameRoute
  AuthenticatedLearnProgressRoute: typeof AuthenticatedLearnProgressRoute
  AuthenticatedLearnQuizRoute: typeof AuthenticatedLearnQuizRoute
  AuthenticatedPlayComputerRoute: typeof AuthenticatedPlayComputerRoute
  AuthenticatedPlayFriendsRoute: typeof AuthenticatedPlayFriendsRoute
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
  AuthenticatedPlayIndexRoute: typeof AuthenticatedPlayIndexRoute
  AuthenticatedGameGameIdReplayRoute: typeof AuthenticatedGameGameIdReplayRoute
  AuthenticatedLearnCategoryCategoryIdRoute: typeof AuthenticatedLearnCategoryCategoryIdRoute
  AuthenticatedLearnLessonLessonIdRoute: typeof AuthenticatedLearnLessonLessonIdRoute
  AuthenticatedLearnLevel1SkillIdRoute: typeof AuthenticatedLearnLevel1SkillIdRoute
  AuthenticatedLearnLevel10SkillIdRoute: typeof AuthenticatedLearnLevel10SkillIdRoute
  AuthenticatedLearnLevel2SkillIdRoute: typeof AuthenticatedLearnLevel2SkillIdRoute
  AuthenticatedLearnLevel3SkillIdRoute: typeof AuthenticatedLearnLevel3SkillIdRoute
  AuthenticatedLearnLevel4SkillIdRoute: typeof AuthenticatedLearnLevel4SkillIdRoute
  AuthenticatedLearnLevel5SkillIdRoute: typeof AuthenticatedLearnLevel5SkillIdRoute
  AuthenticatedLearnLevel6SkillIdRoute: typeof AuthenticatedLearnLevel6SkillIdRoute
  AuthenticatedLearnLevel7SkillIdRoute: typeof AuthenticatedLearnLevel7SkillIdRoute
  AuthenticatedLearnLevel8SkillIdRoute: typeof AuthenticatedLearnLevel8SkillIdRoute
  AuthenticatedLearnLevel9SkillIdRoute: typeof AuthenticatedLearnLevel9SkillIdRoute
  AuthenticatedGameGameIdIndexRoute: typeof AuthenticatedGameGameIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedLearnDailyPuzzleRoute: AuthenticatedLearnDailyPuzzleRoute,
  AuthenticatedLearnInteractiveSampleRoute:
    AuthenticatedLearnInteractiveSampleRoute,
  AuthenticatedLearnPracticeGameRoute: AuthenticatedLearnPracticeGameRoute,
  AuthenticatedLearnProgressRoute: AuthenticatedLearnProgressRoute,
  AuthenticatedLearnQuizRoute: AuthenticatedLearnQuizRoute,
  AuthenticatedPlayComputerRoute: AuthenticatedPlayComputerRoute,
  AuthenticatedPlayFriendsRoute: AuthenticatedPlayFriendsRoute,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
  AuthenticatedPlayIndexRoute: AuthenticatedPlayIndexRoute,
  AuthenticatedGameGameIdReplayRoute: AuthenticatedGameGameIdReplayRoute,
  AuthenticatedLearnCategoryCategoryIdRoute:
    AuthenticatedLearnCategoryCategoryIdRoute,
  AuthenticatedLearnLessonLessonIdRoute: AuthenticatedLearnLessonLessonIdRoute,
  AuthenticatedLearnLevel1SkillIdRoute: AuthenticatedLearnLevel1SkillIdRoute,
  AuthenticatedLearnLevel10SkillIdRoute: AuthenticatedLearnLevel10SkillIdRoute,
  AuthenticatedLearnLevel2SkillIdRoute: AuthenticatedLearnLevel2SkillIdRoute,
  AuthenticatedLearnLevel3SkillIdRoute: AuthenticatedLearnLevel3SkillIdRoute,
  AuthenticatedLearnLevel4SkillIdRoute: AuthenticatedLearnLevel4SkillIdRoute,
  AuthenticatedLearnLevel5SkillIdRoute: AuthenticatedLearnLevel5SkillIdRoute,
  AuthenticatedLearnLevel6SkillIdRoute: AuthenticatedLearnLevel6SkillIdRoute,
  AuthenticatedLearnLevel7SkillIdRoute: AuthenticatedLearnLevel7SkillIdRoute,
  AuthenticatedLearnLevel8SkillIdRoute: AuthenticatedLearnLevel8SkillIdRoute,
  AuthenticatedLearnLevel9SkillIdRoute: AuthenticatedLearnLevel9SkillIdRoute,
  AuthenticatedGameGameIdIndexRoute: AuthenticatedGameGameIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
