import type { ChessLesson, DailyPuzzle, LearnCategory, QuizQuestion } from "./types";

export const START_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";

export const LESSONS: ChessLesson[] = [
  {
    id: "the-board",
    title: "The Chessboard",
    category: "basics",
    difficulty: "beginner",
    description: "Ranks, files, squares and how a game begins.",
    prerequisites: [],
    steps: [
      {
        kind: "info",
        title: "64 squares, light and dark",
        body: [
          "A chessboard has 8 rows called ranks (numbered 1 to 8) and 8 columns called files (lettered a to h).",
          "Every square has a name made of its file and rank, like e4 or g7. White always starts at the bottom, on ranks 1 and 2.",
          "A light square is always on the right-hand side nearest each player.",
        ],
        fen: START_FEN,
      },
      {
        kind: "quiz",
        title: "Name the square",
        question: "Which square is on the e-file and the 4th rank?",
        options: ["4e", "e4", "d5", "e5"],
        answerIndex: 1,
        explanation: "Square names are written file first, then rank: e4.",
      },
      {
        kind: "move",
        title: "The first move",
        body: ["White always moves first. Opening with the e-pawn frees the queen and bishop at once."],
        fen: START_FEN,
        solution: ["e4"],
        instruction: "Move the white pawn from e2 two squares forward to e4.",
        success: "That is the most popular first move in chess — it grabs the centre immediately.",
        retry: "Click the pawn on e2, then click the square e4.",
      },
    ],
  },
  {
    id: "board-setup",
    title: "Board Setup",
    category: "setup",
    difficulty: "beginner",
    description: "Where every piece belongs at the start of a game.",
    prerequisites: ["the-board"],
    steps: [
      {
        kind: "info",
        title: "The starting position",
        body: [
          "Rooks sit in the corners, then knights, then bishops. The queen takes her own colour — the white queen on the light square d1, the black queen on the dark square d8.",
          "The king stands next to her on e1 and e8. All eight pawns fill the rank in front.",
        ],
        fen: START_FEN,
      },
      {
        kind: "move",
        title: "Put the king home",
        body: ["The white king belongs on e1, right beside the queen on d1."],
        fen: "7k/8/8/8/8/8/8/3K4 w - - 0 1",
        solution: ["Ke1"],
        instruction: "Move the white king to e1.",
        success: "Correct — e1 is the white king's starting square.",
        retry: "The king moves one square at a time. Head towards e1.",
      },
      {
        kind: "quiz",
        title: "Queen placement",
        question: "Which square does the black queen start on?",
        options: ["e8", "d8", "d1", "c8"],
        answerIndex: 1,
        explanation: "The queen takes her own colour: the black queen starts on the dark square d8.",
      },
    ],
  },
  {
    id: "turns-and-capturing",
    title: "Turns & Capturing",
    category: "basics",
    difficulty: "beginner",
    description: "Taking turns, capturing pieces and reading the board.",
    prerequisites: ["the-board"],
    steps: [
      {
        kind: "info",
        title: "One move each",
        body: [
          "White moves, then Black, and so on. You must move on your turn — passing is not allowed.",
          "A capture happens when you move onto a square occupied by an enemy piece. The captured piece leaves the board.",
        ],
      },
      {
        kind: "move",
        title: "Make a capture",
        body: ["Pawns move straight ahead, but they capture diagonally."],
        fen: "7k/8/8/3p4/4P3/8/8/4K3 w - - 0 1",
        solution: ["exd5"],
        instruction: "Capture the black pawn on d5 with your e4 pawn.",
        success: "Nice — pawns capture one square diagonally forward.",
        retry: "A pawn never captures straight ahead. Take diagonally.",
      },
    ],
  },
  {
    id: "the-pawn",
    title: "The Pawn",
    category: "pieces",
    difficulty: "beginner",
    description: "The smallest piece, with the most special rules.",
    prerequisites: ["turns-and-capturing"],
    steps: [
      {
        kind: "info",
        title: "How the pawn moves",
        body: [
          "A pawn moves one square straight forward, or two squares on its very first move.",
          "It captures one square diagonally forward, and it can never move backwards.",
        ],
      },
      {
        kind: "move",
        title: "The double step",
        body: ["From its starting square a pawn may leap two squares."],
        fen: "7k/8/8/8/8/8/4P3/4K3 w - - 0 1",
        solution: ["e4"],
        instruction: "Move the pawn two squares forward, from e2 to e4.",
        success: "That double step is only allowed from the pawn's starting rank.",
        retry: "Click the pawn on e2, then the square e4.",
      },
      {
        kind: "quiz",
        title: "Pawn rules",
        question: "How does a pawn capture?",
        options: ["Straight forward", "One square diagonally forward", "Sideways", "Backwards"],
        answerIndex: 1,
        explanation: "Pawns push straight but capture diagonally — that is what makes pawn chains strong.",
      },
    ],
  },
  {
    id: "the-knight",
    title: "The Knight",
    category: "pieces",
    difficulty: "beginner",
    description: "The only piece that jumps over others.",
    prerequisites: ["the-pawn"],
    steps: [
      {
        kind: "info",
        title: "The L-shape",
        body: [
          "A knight moves two squares in one direction and then one square at a right angle — an L-shape.",
          "It is the only piece that can jump over anything standing in the way.",
        ],
      },
      {
        kind: "move",
        title: "Move the knight",
        body: ["From a1 the knight has just two squares available: b3 and c2."],
        fen: "7k/8/8/8/8/8/8/N3K3 w - - 0 1",
        solution: ["Nb3"],
        instruction: "Move the knight to b3.",
        success: "Correct! Two squares up, one square across — a perfect L.",
        retry: "Look for the L-shape: two squares one way, one square perpendicular.",
      },
      {
        kind: "quiz",
        title: "Knight facts",
        question: "Which piece can jump over other pieces?",
        options: ["Bishop", "Knight", "Rook", "Queen"],
        answerIndex: 1,
        explanation: "Only the knight jumps. Everything else is blocked by pieces in the way.",
      },
    ],
  },
  {
    id: "the-bishop",
    title: "The Bishop",
    category: "pieces",
    difficulty: "beginner",
    description: "A long-range piece that never changes colour.",
    prerequisites: ["the-knight"],
    steps: [
      {
        kind: "info",
        title: "Diagonals only",
        body: [
          "A bishop slides any number of free squares along a diagonal.",
          "Because of that, each bishop stays on one colour of square for the whole game.",
        ],
      },
      {
        kind: "move",
        title: "Slide the bishop",
        body: ["From c1 the bishop can travel up the long dark diagonal."],
        fen: "7k/8/8/8/8/8/8/2B1K3 w - - 0 1",
        solution: ["Bg5"],
        instruction: "Move the bishop from c1 to g5.",
        success: "Bishops love open diagonals — the longer the better.",
        retry: "Follow the diagonal from c1: d2, e3, f4, g5.",
      },
    ],
  },
  {
    id: "the-rook",
    title: "The Rook",
    category: "pieces",
    difficulty: "beginner",
    description: "Straight lines, open files and back-rank power.",
    prerequisites: ["the-bishop"],
    steps: [
      {
        kind: "info",
        title: "Ranks and files",
        body: [
          "A rook moves any number of free squares in a straight line: along a rank or along a file.",
          "Rooks become strong when files open up and when they reach the enemy's back rank.",
        ],
      },
      {
        kind: "move",
        title: "Take the open file",
        body: ["Travel up the a-file and give check along the 8th rank."],
        fen: "7k/8/8/8/8/8/8/R3K3 w - - 0 1",
        solution: ["Ra8+"],
        instruction: "Move the rook to a8 and put the black king in check.",
        success: "The rook now attacks the king along the whole 8th rank.",
        retry: "Slide the rook straight up the a-file to a8.",
      },
    ],
  },
  {
    id: "the-queen",
    title: "The Queen",
    category: "pieces",
    difficulty: "beginner",
    description: "The most powerful piece on the board.",
    prerequisites: ["the-rook"],
    steps: [
      {
        kind: "info",
        title: "Rook plus bishop",
        body: [
          "The queen combines the rook and bishop: she moves any number of free squares along ranks, files and diagonals.",
          "She is worth about nine pawns, so keep her safe — do not chase small gains with her early.",
        ],
      },
      {
        kind: "move",
        title: "Give check",
        body: ["The queen can switch from a file to a rank in a single move."],
        fen: "7k/8/8/8/8/8/8/3QK3 w - - 0 1",
        solution: ["Qd8+"],
        instruction: "Move the queen to d8 to check the black king.",
        success: "One move, and the queen rules the whole 8th rank.",
        retry: "Slide the queen straight up the d-file.",
      },
    ],
  },
  {
    id: "the-king",
    title: "The King",
    category: "pieces",
    difficulty: "beginner",
    description: "Slow, precious, and surprisingly strong in the endgame.",
    prerequisites: ["the-queen"],
    steps: [
      {
        kind: "info",
        title: "One square at a time",
        body: [
          "The king moves one square in any direction, and may never step onto a square attacked by an enemy piece.",
          "The king is never captured — the game ends when he cannot escape check.",
        ],
      },
      {
        kind: "move",
        title: "Step forward",
        body: ["In the endgame an active king is a real fighting piece."],
        fen: "7k/8/8/8/8/8/8/4K3 w - - 0 1",
        solution: ["Ke2"],
        instruction: "Move the king one square forward, to e2.",
        success: "Good. In endgames you should march the king towards the action.",
        retry: "The king moves exactly one square. Try e2.",
      },
    ],
  },
  {
    id: "what-is-check",
    title: "What Is Check?",
    category: "check",
    difficulty: "beginner",
    description: "Attacking the enemy king — and what that forces.",
    prerequisites: ["the-king"],
    steps: [
      {
        kind: "info",
        title: "The king under attack",
        body: [
          "A king is in check when an enemy piece attacks his square.",
          "Check is not the end of the game — but the player in check must deal with it immediately.",
        ],
      },
      {
        kind: "move",
        title: "Deliver check",
        body: ["Bring the queen to the back rank."],
        fen: "6k1/8/8/8/8/8/8/3QK3 w - - 0 1",
        solution: ["Qd8+"],
        instruction: "Play a move that puts the black king in check.",
        success: "The black king is attacked — that is check.",
        retry: "Find a queen move that attacks the king on g8.",
      },
    ],
  },
  {
    id: "escaping-check",
    title: "How to Escape Check",
    category: "check",
    difficulty: "beginner",
    description: "Move, capture or block — the only three answers.",
    prerequisites: ["what-is-check"],
    steps: [
      {
        kind: "info",
        title: "Three ways out",
        body: [
          "1. Move the king to a safe square.",
          "2. Capture the checking piece.",
          "3. Block the attack with another piece (impossible against a knight or a contact check).",
        ],
      },
      {
        kind: "move",
        title: "Block the check",
        body: ["Black is in check from the rook on e2. There is a clean blocking move."],
        fen: "4k3/8/7r/8/8/8/4R3/4K3 b - - 0 1",
        orientation: "black",
        solution: ["Re6"],
        instruction: "Block the check by placing the black rook on e6.",
        success: "Blocking works because the rook attacks in a straight line.",
        retry: "Put a piece between the rook on e2 and the king on e8.",
      },
      {
        kind: "move",
        title: "Capture the attacker",
        body: ["White is in check from the black queen — and she is undefended."],
        fen: "4k3/8/8/8/8/8/4q3/4K3 w - - 0 1",
        solution: ["Kxe2"],
        instruction: "Escape the check by capturing the queen.",
        success: "Taking the checking piece is always worth looking for first.",
        retry: "The queen on e2 is right next to your king and nothing defends her.",
      },
    ],
  },
  {
    id: "checkmate-and-stalemate",
    title: "Checkmate & Stalemate",
    category: "check",
    difficulty: "beginner",
    description: "How games are won — and how wins get thrown away.",
    prerequisites: ["escaping-check"],
    steps: [
      {
        kind: "info",
        title: "Checkmate ends the game",
        body: [
          "Checkmate is a check with no escape: the king cannot move, the attacker cannot be captured, and the line cannot be blocked.",
          "Stalemate is different: the player to move is NOT in check but has no legal move at all. That is a draw, even if you are a queen up.",
        ],
      },
      {
        kind: "move",
        title: "Finish the game",
        body: ["The black king is trapped behind his own pawns."],
        fen: "6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1",
        solution: ["Ra8#"],
        instruction: "Deliver checkmate in one move.",
        success: "Checkmate! The king has no escape squares — his own pawns block him in.",
        retry: "Look at the empty 8th rank and the pawns locking the king in.",
      },
      {
        kind: "quiz",
        title: "Stalemate",
        question: "You are a queen up, the enemy king is not in check, and he has no legal move. What is the result?",
        options: ["You win", "Draw by stalemate", "The opponent must pass", "You win on time"],
        answerIndex: 1,
        explanation: "No check plus no legal move equals stalemate — a draw. Always leave the enemy king a square when mating.",
      },
    ],
  },
  {
    id: "castling",
    title: "Castling",
    category: "special",
    difficulty: "beginner",
    description: "The only move where two pieces move at once.",
    prerequisites: ["checkmate-and-stalemate"],
    steps: [
      {
        kind: "info",
        title: "Conditions",
        body: [
          "The king and that rook must not have moved yet, the squares between them must be empty, and the king may not be in check, pass through check, or land in check.",
          "Kingside castling (O-O) is short and fast. Queenside castling (O-O-O) takes the king a little further.",
        ],
      },
      {
        kind: "move",
        title: "Castle kingside",
        body: ["Move the king two squares towards the h1 rook; the rook jumps to f1."],
        fen: "r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1",
        solution: ["O-O"],
        instruction: "Castle kingside: drag the king from e1 to g1.",
        success: "The king is tucked away and the rook is developed in one move.",
        retry: "Move the king two squares to the right, onto g1.",
      },
      {
        kind: "move",
        title: "Castle queenside",
        body: ["Now the long side: the king goes to c1 and the a1 rook lands on d1."],
        fen: "r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1",
        solution: ["O-O-O"],
        instruction: "Castle queenside: move the king from e1 to c1.",
        success: "Queenside castling puts a rook on the central d-file straight away.",
        retry: "Move the king two squares to the left, onto c1.",
      },
    ],
  },
  {
    id: "en-passant",
    title: "En Passant",
    category: "special",
    difficulty: "beginner",
    description: "The capture in passing that surprises every beginner.",
    prerequisites: ["castling"],
    steps: [
      {
        kind: "info",
        title: "In passing",
        body: [
          "If an enemy pawn uses its two-square jump to land right beside your pawn, you may capture it as if it had moved only one square.",
          "The capture is only available on the very next move — miss it and the chance is gone forever.",
        ],
      },
      {
        kind: "move",
        title: "Capture in passing",
        body: ["Black has just played d7-d5, jumping past your e5 pawn."],
        fen: "4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 2",
        solution: ["exd6"],
        instruction: "Capture the d5 pawn en passant by moving your pawn to d6.",
        success: "Your pawn lands on d6 and the black pawn is removed — that is en passant.",
        retry: "Move the e5 pawn diagonally to the empty square d6.",
      },
    ],
  },
  {
    id: "pawn-promotion",
    title: "Pawn Promotion",
    category: "special",
    difficulty: "beginner",
    description: "Turn a humble pawn into a queen.",
    prerequisites: ["en-passant"],
    steps: [
      {
        kind: "info",
        title: "Reaching the end",
        body: [
          "A pawn that reaches the far rank must immediately become a queen, rook, bishop or knight.",
          "Almost always choose the queen. Underpromotion to a knight is rare, but it can give check when a queen cannot.",
        ],
      },
      {
        kind: "move",
        title: "Promote the pawn",
        body: ["One step to go."],
        fen: "8/P7/8/7k/8/8/8/4K3 w - - 0 1",
        solution: ["a8=Q"],
        instruction: "Push the pawn to a8 and promote it to a queen.",
        success: "A new queen appears — the pawn is gone and the game is decided.",
        retry: "Move the a7 pawn to a8 and pick the queen in the dialog.",
      },
    ],
  },
  {
    id: "tactic-fork",
    title: "The Fork",
    category: "tactics",
    difficulty: "intermediate",
    description: "One piece attacking two targets at the same time.",
    prerequisites: ["pawn-promotion"],
    steps: [
      {
        kind: "info",
        title: "Two targets, one move",
        body: [
          "A fork attacks two or more pieces at once. Knights are the classic forking piece because their attack cannot be blocked.",
          "The strongest forks hit the king — the opponent must answer the check and loses the other piece.",
        ],
      },
      {
        kind: "move",
        title: "Find the fork",
        body: ["You are White. The black king and queen can be hit by the same knight move."],
        fen: "r4rk1/ppp2p1p/8/3q4/6N1/8/PPP2PPP/R3R1K1 w - - 0 1",
        solution: ["Nf6+", "Kh8", "Nxd5"],
        instruction: "Play the knight fork, then collect the queen.",
        success: "The check forced the king to move, and the queen fell next move.",
        retry: "Which knight move attacks the king on g8 and the queen on d5 at once?",
      },
    ],
  },
  {
    id: "tactic-pin",
    title: "The Pin",
    category: "tactics",
    difficulty: "intermediate",
    description: "Freezing a piece in front of something more valuable.",
    prerequisites: ["tactic-fork"],
    steps: [
      {
        kind: "info",
        title: "Stuck in place",
        body: [
          "A pin attacks a piece that cannot move because something more valuable sits behind it.",
          "When the king is behind, the pinned piece is completely paralysed — it is illegal to move it.",
        ],
      },
      {
        kind: "move",
        title: "Pin the knight",
        body: ["The black knight on c6 stands in front of the king on e8."],
        fen: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1",
        solution: ["Bb5"],
        instruction: "Develop the bishop so it pins the knight against the king.",
        success: "That is the Ruy Lopez pin — the knight on c6 is now frozen.",
        retry: "Find the bishop move that lines up with c6 and e8.",
      },
    ],
  },
  {
    id: "tactic-skewer",
    title: "The Skewer",
    category: "tactics",
    difficulty: "intermediate",
    description: "A pin the other way around.",
    prerequisites: ["tactic-pin"],
    steps: [
      {
        kind: "info",
        title: "Valuable piece in front",
        body: [
          "In a skewer the valuable piece is attacked first. When it moves away, you capture what was hiding behind it.",
          "Rooks, bishops and queens are the skewering pieces because they attack along lines.",
        ],
      },
      {
        kind: "move",
        title: "Win the queen",
        body: ["The black king and queen share the a-file."],
        fen: "8/8/q7/8/k7/8/8/1R2K3 w - - 0 1",
        solution: ["Ra1+", "Kb5", "Rxa6"],
        instruction: "Skewer the king and queen, then take the queen.",
        success: "The king had to step aside, and the queen was lost.",
        retry: "Put the rook on the a-file with check.",
      },
    ],
  },
  {
    id: "tactic-discovered-attack",
    title: "Discovered Attack",
    category: "tactics",
    difficulty: "intermediate",
    description: "Move one piece, unleash another.",
    prerequisites: ["tactic-skewer"],
    steps: [
      {
        kind: "info",
        title: "Two attacks in one",
        body: [
          "When a piece steps out of the way, the piece behind it suddenly attacks. If the moving piece also gives check, the opponent is helpless.",
          "Look for your own pieces standing in front of a rook, bishop or queen.",
        ],
      },
      {
        kind: "move",
        title: "Discover the rook",
        body: ["Your rook on e1 is staring at the black queen — but the knight is in the way."],
        fen: "4k3/4q3/8/8/4N3/8/8/4R1K1 w - - 0 1",
        solution: ["Nf6+", "Kd8", "Rxe7"],
        instruction: "Move the knight with check, then win the queen.",
        success: "The knight checked the king while uncovering the rook's attack on the queen.",
        retry: "Find a knight move that gives check and clears the e-file.",
      },
    ],
  },
  {
    id: "tactic-back-rank",
    title: "Back-Rank Mate",
    category: "tactics",
    difficulty: "intermediate",
    description: "The mate that punishes a sleepy king.",
    prerequisites: ["tactic-discovered-attack"],
    steps: [
      {
        kind: "info",
        title: "Trapped by his own pawns",
        body: [
          "A castled king with three untouched pawns in front of him can be mated along the back rank by a single rook or queen.",
          "The cure is simple: make a little escape square by pushing one pawn — often h2-h3.",
        ],
      },
      {
        kind: "move",
        title: "Mate in one",
        body: ["Black's back rank is undefended."],
        fen: "6k1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1",
        solution: ["Ra8#"],
        instruction: "Deliver back-rank mate.",
        success: "Checkmate — the pawns on f7, g7 and h7 seal the king's fate.",
        retry: "Bring your rook to the empty 8th rank.",
      },
    ],
  },
  {
    id: "opening-principles",
    title: "Opening Principles",
    category: "openings",
    difficulty: "intermediate",
    description: "Six rules that beat memorising variations.",
    prerequisites: ["pawn-promotion"],
    steps: [
      {
        kind: "info",
        title: "The six rules",
        body: [
          "1. Control the centre — the squares e4, d4, e5 and d5.",
          "2. Develop your knights and bishops quickly, towards the centre.",
          "3. Castle early to tuck the king away.",
          "4. Do not move the same piece twice in the opening without a reason.",
          "5. Do not bring the queen out too early — she will just get chased.",
          "6. Connect your rooks by clearing the back rank.",
        ],
        fen: START_FEN,
      },
      {
        kind: "move",
        title: "Develop and castle",
        body: ["Play a natural opening: centre pawn, knight, bishop, castle."],
        fen: START_FEN,
        solution: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "O-O"],
        instruction: "Play e4, then Nf3, then Bc4, then castle kingside.",
        success: "Four healthy developing moves and the king is safe. That is a perfect opening.",
        retry: "Follow the principles: centre pawn first, then knight, then bishop, then castle.",
      },
      {
        kind: "quiz",
        title: "Opening mistakes",
        question: "Which of these is the worst opening habit?",
        options: [
          "Developing knights before bishops",
          "Chasing pawns with the queen on move three",
          "Castling on move six",
          "Playing d4 on move one",
        ],
        answerIndex: 1,
        explanation: "An early queen sortie loses time — every developing move your opponent plays also attacks her.",
      },
    ],
  },
  {
    id: "opening-italian",
    title: "Italian Game",
    category: "openings",
    difficulty: "intermediate",
    description: "The friendliest way to attack f7.",
    prerequisites: ["opening-principles"],
    steps: [
      {
        kind: "info",
        title: "Purpose",
        body: [
          "1.e4 e5 2.Nf3 Nc6 3.Bc4 — the bishop eyes the weak f7 square and the knight pressures e5.",
          "Ideas: castle quickly, prepare d3 and c3, then build a big centre with d4.",
          "Common mistake: grabbing on f7 too early with a sacrifice that does not work.",
        ],
        fen: START_FEN,
      },
      {
        kind: "move",
        title: "Play the line",
        body: ["Follow the main moves of the Italian Game."],
        fen: START_FEN,
        solution: ["e4", "e5", "Nf3", "Nc6", "Bc4"],
        instruction: "Play 1.e4, 2.Nf3 and 3.Bc4.",
        success: "That is the Italian Game — simple, sound and great for attacking players.",
        retry: "The moves are e4, then Nf3, then Bc4.",
      },
    ],
  },
  {
    id: "opening-ruy-lopez",
    title: "Ruy Lopez",
    category: "openings",
    difficulty: "intermediate",
    description: "The Spanish bishop and the pressure on c6.",
    prerequisites: ["opening-italian"],
    steps: [
      {
        kind: "info",
        title: "Purpose",
        body: [
          "1.e4 e5 2.Nf3 Nc6 3.Bb5 — the bishop attacks the defender of the e5 pawn.",
          "Ideas: castle, play c3 and d4, and squeeze in the centre for a long game.",
          "Common mistake: expecting to win a pawn immediately with Bxc6 — after 4...dxc6 Black is fine.",
        ],
        fen: START_FEN,
      },
      {
        kind: "move",
        title: "Play the line",
        body: ["Reach the starting position of the Ruy Lopez."],
        fen: START_FEN,
        solution: ["e4", "e5", "Nf3", "Nc6", "Bb5"],
        instruction: "Play 1.e4, 2.Nf3 and 3.Bb5.",
        success: "The Spanish Opening — the most played opening at the top level for over a century.",
        retry: "The third move puts the bishop on b5, attacking the knight.",
      },
    ],
  },
  {
    id: "opening-queens-gambit",
    title: "Queen's Gambit",
    category: "openings",
    difficulty: "intermediate",
    description: "Offer a pawn, take the centre.",
    prerequisites: ["opening-principles"],
    steps: [
      {
        kind: "info",
        title: "Purpose",
        body: [
          "1.d4 d5 2.c4 — White offers a wing pawn to pull Black's d5 pawn away from the centre.",
          "Ideas: recapture the centre with e4 later, develop with Nc3 and Nf3.",
          "Common mistake: thinking Black can hold the pawn after 2...dxc4 — trying to keep it with b5 loses material.",
        ],
        fen: START_FEN,
      },
      {
        kind: "move",
        title: "Play the line",
        body: ["Offer the gambit."],
        fen: START_FEN,
        solution: ["d4", "d5", "c4"],
        instruction: "Play 1.d4 and 2.c4.",
        success: "That is the Queen's Gambit — not really a gambit, since White usually wins the pawn back.",
        retry: "First the d-pawn two squares, then the c-pawn two squares.",
      },
    ],
  },
  {
    id: "opening-sicilian",
    title: "Sicilian Defense",
    category: "openings",
    difficulty: "intermediate",
    description: "Black's sharpest answer to 1.e4.",
    prerequisites: ["opening-principles"],
    steps: [
      {
        kind: "info",
        title: "Purpose",
        body: [
          "1.e4 c5 — Black fights for the centre from the side and unbalances the game straight away.",
          "Ideas: trade the c-pawn for White's d-pawn, then use the half-open c-file for counterplay.",
          "Common mistake: playing slowly. The Sicilian demands active piece play.",
        ],
        fen: START_FEN,
      },
      {
        kind: "move",
        title: "Play as Black",
        body: ["White has opened 1.e4. Answer with the Sicilian."],
        fen: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
        orientation: "black",
        solution: ["c5", "Nf3", "d6"],
        instruction: "Play 1...c5 and then 2...d6.",
        success: "You have reached the Sicilian Defense, the most popular reply to 1.e4.",
        retry: "The Sicilian starts with the c-pawn going two squares.",
      },
    ],
  },
  {
    id: "endgame-queen-mate",
    title: "King & Queen vs King",
    category: "endgame",
    difficulty: "advanced",
    description: "The first checkmate every player must know.",
    prerequisites: ["checkmate-and-stalemate"],
    steps: [
      {
        kind: "info",
        title: "The technique",
        body: [
          "Use the queen to shrink the enemy king's box, one rank or file at a time, then bring your own king up to support the mate.",
          "Watch out for stalemate: never take away every square unless it is check.",
        ],
      },
      {
        kind: "move",
        title: "Mate in one",
        body: ["Your king already guards g7, g8's neighbours and h7."],
        fen: "7k/8/6K1/8/8/8/8/1Q6 w - - 0 1",
        solution: ["Qb8#"],
        instruction: "Deliver checkmate with the queen.",
        success: "Checkmate. The king on g6 covers the escape squares while the queen delivers the blow.",
        retry: "Bring the queen to the 8th rank where your king already covers the escapes.",
      },
    ],
  },
  {
    id: "endgame-rook-mate",
    title: "King & Rook vs King",
    category: "endgame",
    difficulty: "advanced",
    description: "Push the king to the edge and finish.",
    prerequisites: ["endgame-queen-mate"],
    steps: [
      {
        kind: "info",
        title: "The technique",
        body: [
          "The rook cuts the enemy king off along a rank or file. Your king walks up to stand opposite his — the opposition — and then the rook checks.",
          "The mate always happens on an edge of the board.",
        ],
      },
      {
        kind: "move",
        title: "Mate in one",
        body: ["The kings are in opposition and the black king is on the edge."],
        fen: "7k/8/6K1/8/8/8/8/1R6 w - - 0 1",
        solution: ["Rb8#"],
        instruction: "Deliver checkmate with the rook.",
        success: "Checkmate — the rook checks along the 8th rank and your king takes every escape square.",
        retry: "Check along the 8th rank.",
      },
    ],
  },
  {
    id: "endgame-pawn",
    title: "King & Pawn vs King",
    category: "endgame",
    difficulty: "advanced",
    description: "Opposition, king activity and promotion.",
    prerequisites: ["endgame-rook-mate"],
    steps: [
      {
        kind: "info",
        title: "Opposition",
        body: [
          "When the kings stand on the same file with one square between them, the player who does NOT have to move holds the opposition — and usually wins the key squares.",
          "Rule of thumb: push your king in front of the pawn, not the pawn in front of your king.",
        ],
      },
      {
        kind: "move",
        title: "Queen the pawn",
        body: ["Your king shelters the pawn and the black king is far away."],
        fen: "8/3P4/3K4/8/8/8/8/6k1 w - - 0 1",
        solution: ["d8=Q"],
        instruction: "Promote the pawn.",
        success: "A new queen, and the rest is the king-and-queen mate you already know.",
        retry: "Push the d7 pawn to d8 and choose the queen.",
      },
      {
        kind: "quiz",
        title: "Opposition",
        question: "Kings face each other on e4 and e6 with one square between them. Who holds the opposition?",
        options: ["The player to move", "The player NOT to move", "White always", "Neither"],
        answerIndex: 1,
        explanation: "The side that must move has to give way — so the player not to move holds the opposition.",
      },
    ],
  },
];

export const CATEGORIES: LearnCategory[] = [
  {
    id: "basics",
    title: "Chess Basics",
    icon: "♟",
    description: "Learn how the chessboard works, how turns run, and how games begin.",
    difficulty: "beginner",
    lessonIds: ["the-board", "turns-and-capturing"],
  },
  {
    id: "pieces",
    title: "Chess Pieces",
    icon: "♞",
    description: "Meet every piece, its value and its personality.",
    difficulty: "beginner",
    lessonIds: ["the-pawn", "the-knight", "the-bishop", "the-rook", "the-queen", "the-king"],
  },
  {
    id: "setup",
    title: "Board Setup",
    icon: "♜",
    description: "Ranks, files and where each piece belongs at the start.",
    difficulty: "beginner",
    lessonIds: ["board-setup"],
  },
  {
    id: "check",
    title: "Check & Checkmate",
    icon: "♚",
    description: "Check, the three escapes, checkmate and the stalemate trap.",
    difficulty: "beginner",
    lessonIds: ["what-is-check", "escaping-check", "checkmate-and-stalemate"],
  },
  {
    id: "special",
    title: "Special Moves",
    icon: "♔",
    description: "Castling, en passant and pawn promotion, step by step.",
    difficulty: "beginner",
    lessonIds: ["castling", "en-passant", "pawn-promotion"],
  },
  {
    id: "tactics",
    title: "Chess Tactics",
    icon: "⚔",
    description: "Forks, pins, skewers, discovered attacks and back-rank mates.",
    difficulty: "intermediate",
    lessonIds: [
      "tactic-fork",
      "tactic-pin",
      "tactic-skewer",
      "tactic-discovered-attack",
      "tactic-back-rank",
    ],
  },
  {
    id: "openings",
    title: "Opening Principles",
    icon: "♘",
    description: "Six rules, then five beginner-friendly openings with their real ideas.",
    difficulty: "intermediate",
    lessonIds: [
      "opening-principles",
      "opening-italian",
      "opening-ruy-lopez",
      "opening-queens-gambit",
      "opening-sicilian",
    ],
  },
  {
    id: "endgame",
    title: "Endgame Basics",
    icon: "♖",
    description: "The three endings you must know before anything else.",
    difficulty: "advanced",
    lessonIds: ["endgame-queen-mate", "endgame-rook-mate", "endgame-pawn"],
  },
  {
    id: "practice",
    title: "Practice",
    icon: "🎯",
    description: "Put it together against Stockfish at your own level.",
    difficulty: "beginner",
    lessonIds: [],
    href: "/play/computer",
  },
  {
    id: "quiz",
    title: "Chess Quiz",
    icon: "❓",
    description: "Ten questions covering the rules, tactics and openings.",
    difficulty: "beginner",
    lessonIds: [],
    href: "/learn/quiz",
  },
  {
    id: "daily",
    title: "Daily Puzzle",
    icon: "🔥",
    description: "A fresh position every day. Find the best move.",
    difficulty: "intermediate",
    lessonIds: [],
    href: "/learn/daily-puzzle",
  },
];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: "q1",
    question: "What piece can jump over other pieces?",
    options: ["Bishop", "Knight", "Rook", "Queen"],
    answerIndex: 1,
    explanation: "The knight is the only piece that jumps.",
  },
  {
    id: "q2",
    question: "How many squares does a chessboard have?",
    options: ["36", "49", "64", "81"],
    answerIndex: 2,
    explanation: "Eight ranks times eight files equals 64 squares.",
  },
  {
    id: "q3",
    question: "Which square does the white queen start on?",
    options: ["e1", "d1", "d8", "c1"],
    answerIndex: 1,
    explanation: "The queen takes her own colour — white queen on the light square d1.",
  },
  {
    id: "q4",
    question: "What happens when a pawn reaches the last rank?",
    options: [
      "It is removed",
      "It stays a pawn",
      "It promotes to any piece except a king",
      "It becomes a king",
    ],
    answerIndex: 2,
    explanation: "Promotion is compulsory: queen, rook, bishop or knight.",
  },
  {
    id: "q5",
    question: "Which of these is NOT a legal way to escape check?",
    options: ["Move the king", "Capture the attacker", "Block the line", "Castle out of check"],
    answerIndex: 3,
    explanation: "You may never castle while in check, through check, or into check.",
  },
  {
    id: "q6",
    question: "The player to move is not in check but has no legal move. What is it?",
    options: ["Checkmate", "Stalemate", "Resignation", "Zugzwang loss"],
    answerIndex: 1,
    explanation: "That is stalemate, and the game is drawn.",
  },
  {
    id: "q7",
    question: "A knight attacks the king and the queen at the same time. What is that called?",
    options: ["A pin", "A skewer", "A fork", "A discovered attack"],
    answerIndex: 2,
    explanation: "One piece attacking two targets is a fork.",
  },
  {
    id: "q8",
    question: "Which opening starts 1.e4 e5 2.Nf3 Nc6 3.Bb5?",
    options: ["Italian Game", "Ruy Lopez", "Scotch Game", "Sicilian Defense"],
    answerIndex: 1,
    explanation: "Bb5 is the Spanish bishop of the Ruy Lopez.",
  },
  {
    id: "q9",
    question: "Roughly how many pawns is a rook worth?",
    options: ["3", "5", "7", "9"],
    answerIndex: 1,
    explanation: "Standard values: pawn 1, knight and bishop 3, rook 5, queen 9.",
  },
  {
    id: "q10",
    question: "What is the best way to prevent a back-rank mate?",
    options: [
      "Keep the queen at home",
      "Give the king an escape square with a pawn move",
      "Never castle",
      "Trade all the rooks immediately",
    ],
    answerIndex: 1,
    explanation: "A small pawn move such as h2-h3 makes an escape square and stops the mate.",
  },
];

export const DAILY_PUZZLES: DailyPuzzle[] = [
  {
    id: "dp-back-rank",
    fen: "6k1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1",
    orientation: "white",
    sideToMove: "White",
    prompt: "Find the best move. You have White.",
    solution: ["Ra8#"],
    idea: "Back-rank mate — the black pawns block their own king.",
  },
  {
    id: "dp-fork",
    fen: "r4rk1/ppp2p1p/8/3q4/6N1/8/PPP2PPP/R3R1K1 w - - 0 1",
    orientation: "white",
    sideToMove: "White",
    prompt: "Find the fork. You have White.",
    solution: ["Nf6+", "Kh8", "Nxd5"],
    idea: "A knight check that also hits the queen wins material by force.",
  },
  {
    id: "dp-skewer",
    fen: "8/8/q7/8/k7/8/8/1R2K3 w - - 0 1",
    orientation: "white",
    sideToMove: "White",
    prompt: "Win material. You have White.",
    solution: ["Ra1+", "Kb5", "Rxa6"],
    idea: "Skewer: check the king and take the queen behind him.",
  },
  {
    id: "dp-discovered",
    fen: "4k3/4q3/8/8/4N3/8/8/4R1K1 w - - 0 1",
    orientation: "white",
    sideToMove: "White",
    prompt: "Find the winning move. You have White.",
    solution: ["Nf6+", "Kd8", "Rxe7"],
    idea: "A discovered attack: the knight checks while the rook hits the queen.",
  },
  {
    id: "dp-queen-mate",
    fen: "7k/8/6K1/8/8/8/8/1Q6 w - - 0 1",
    orientation: "white",
    sideToMove: "White",
    prompt: "Mate in one. You have White.",
    solution: ["Qb8#"],
    idea: "The king covers the escape squares, the queen finishes on the back rank.",
  },
  {
    id: "dp-promotion",
    fen: "8/3P4/3K4/8/8/8/8/6k1 w - - 0 1",
    orientation: "white",
    sideToMove: "White",
    prompt: "Convert your advantage. You have White.",
    solution: ["d8=Q"],
    idea: "Promote immediately — the black king is too far away to stop it.",
  },
  {
    id: "dp-rook-mate",
    fen: "7k/8/6K1/8/8/8/8/1R6 w - - 0 1",
    orientation: "white",
    sideToMove: "White",
    prompt: "Mate in one. You have White.",
    solution: ["Rb8#"],
    idea: "The classic king-and-rook mate on the edge of the board.",
  },
];

export function todayKey(date = new Date()) {
  return date.toISOString().slice(0, 10);
}

export function puzzleForDate(date = new Date()): DailyPuzzle {
  const key = todayKey(date);
  const days = Math.floor(Date.parse(`${key}T00:00:00Z`) / 86_400_000);
  return DAILY_PUZZLES[((days % DAILY_PUZZLES.length) + DAILY_PUZZLES.length) % DAILY_PUZZLES.length]!;
}

export function lessonById(id: string) {
  return LESSONS.find((l) => l.id === id) ?? null;
}

export function categoryById(id: string) {
  return CATEGORIES.find((c) => c.id === id) ?? null;
}

/** Ordered learning path across the whole curriculum. */
export const LEARNING_PATH = LESSONS.map((l) => l.id);
